# -*- coding: utf-8 -*-
"""All site copy, English + Korean. Facts come from the Sept 2026 CV and the Medical, Paper, Study and Deep_Daiv READMEs.
Every string pair is (EN, KO). Inline <b>, <br> and <em> are allowed."""
from urllib.parse import quote

REPO = 'https://github.com/heoneyzi'
EMAIL = 'danieljiheon@yonsei.ac.kr'
GITHUB = 'https://github.com/heoneyzi'
LINKEDIN = 'https://www.linkedin.com/in/jiheonkang'
CV = 'Jiheon_Kang_CV.pdf'
SITE = 'https://heoneyzi.github.io/'
UPDATED = ('Updated September 2026', '2026년 9월 업데이트')


def gh(path):
    parts = path.split('/', 1)
    repositories = {'01_Medical': 'Medical', '02_Paper': 'Paper', '03_Study': 'Study', '04_Deep_Daiv': 'Deep_Daiv'}
    repo = repositories[parts[0]]
    return REPO + '/' + repo + ('/tree/main/' + quote(parts[1], safe='/.') if len(parts) > 1 else '')


# ----------------------------------------------------------------------------------------------- projects
# Order = prev/next order on project pages.
PROJECTS = [
    # ------------------------------------------------------------------------------------------- GDTR
    dict(
        slug='gdtr', dom='dna', icon='dna', short='GDTR',
        kicker=('DNA · Model interpretability · 2026', 'DNA · 모델 해석 · 2026'),
        title=('Where does a DNA model make up its mind?', 'DNA 모델은 어디서 판단을 내릴까?'),
        lede=('A training-free “depth ruler” for the DNA language model Evo 2 — and what it reveals about biology. Follow-up research is ongoing.',
              'DNA 언어모델 Evo 2 안에서 판단이 끝나는 깊이를 재는, 학습이 필요 없는 “깊이 자”와 그 자로 본 생물학. 후속 연구를 진행하고 있습니다.'),
        card_q=('A depth ruler for Evo 2: at which layer does the model settle on each letter of DNA?',
                'Evo 2가 DNA 글자마다 몇 번째 층에서 판단을 끝내는지 재는 “깊이 자”.'),
        card_v='94.6%', card_l=('of the effect kept on an unseen chromosome', '처음 보는 염색체에서도 유지된 효과'),
        outcome=('Oral · ICML 2026 GenBio Workshop', 'ICML 2026 GenBio 워크숍 · Oral'), status='live',
        live_label=('Follow-up ongoing', '후속 연구 중'),
        badge=('Oral · ICML 2026 GenBio', 'ICML 2026 GenBio · Oral'),
        role=('Author', '저자'),
        period=('Apr 2026 – ongoing', '2026.04 – 진행 중'),
        team=('Yoonjin Cho (first author), <b>Jiheon Kang</b>, Subin Park, Prof. Sangwoo Kim (corresponding) · Yonsei University',
              'Yoonjin Cho(제1저자), <b>Jiheon Kang</b>, Subin Park, Prof. Sangwoo Kim(교신저자) · 연세대학교'),
        glance=dict(
            topic=('DNA language models read DNA letter by letter and are already used to judge disease variants — but we rarely know <b>where inside the model</b> that judgement is made.',
                   'DNA 언어모델은 DNA를 한 글자씩 읽고 질병 변이 판정에도 쓰이지만, 그 판단이 <b>모델 안 어디에서</b> 이뤄지는지는 거의 알지 못합니다.'),
            did=('Without retraining, measured the layer at which each DNA letter “settles” in Evo 2 7B, and linked that depth to splice sites, regulatory elements, genes and disease variants.',
                 '모델을 다시 학습하지 않고 Evo 2 7B에서 DNA 글자마다 판단이 “정착”하는 층을 재고, 그 깊이를 스플라이스 자리·조절 영역·유전자·질병 변이와 연결했습니다.'),
            result=('Biology shows up as depth: splice sites settle about <b>2 layers earlier</b> than introns, and the effect carries over to a chromosome the ruler never saw (<b>94.6 %</b>).',
                    '생물학이 깊이로 드러났습니다. 스플라이스 자리는 인트론보다 약 <b>2층 먼저</b> 정착하고, 이 효과는 한 번도 보지 않은 염색체에서도 <b>94.6%</b> 유지됐습니다.'),
        ),
        question=[
            ('Evo 2 is trained only to guess the next letter of DNA, yet researchers already use its internal signals to annotate genomes and score variants. If we knew where along its 32 layers the model resolves each position, we would know which layer to read — and which parts of the genome it understands early or late.',
             'Evo 2는 DNA의 다음 글자를 맞히도록만 학습됐지만, 연구자들은 이미 그 내부 신호로 유전체를 해석하고 변이를 평가합니다. 32개 층 가운데 어디에서 각 위치를 판단하는지 안다면, 어느 층을 읽어야 하는지, 그리고 유전체의 어떤 부분을 일찍 혹은 늦게 이해하는지 알 수 있습니다.'),
        ],
        steps=[
            (('Build a depth ruler', '깊이 자 만들기'),
             ('For every letter, find the first layer whose internal state already points the same way as the final one — its <b>settling depth</b>.',
              '글자마다 내부 상태가 최종 상태와 같은 방향을 가리키기 시작하는 첫 층, 즉 <b>정착 깊이</b>를 찾습니다.')),
            (('Read biology from depth', '깊이로 생물학 읽기'),
             ('Compare settling depth across splice sites, exons, introns, regulatory elements and ClinVar disease variants.',
              '스플라이스 자리, 엑손, 인트론, 조절 영역, ClinVar 질병 변이별로 정착 깊이를 비교합니다.')),
            (('Check that it holds', '일반화 확인'),
             ('Calibrate on chromosome 22, test on held-out chromosome 17, and rule out simple explanations such as prediction uncertainty.',
              '22번 염색체로 기준을 정하고 보지 않은 17번 염색체에서 시험하며, 예측 불확실성 같은 단순한 설명도 배제합니다.')),
            (('Keep going as a team', '팀 후속 연구'),
             ('Our YAICON team (TDiG) widened the ruler into 17 geometric measures; I am now studying what the final layers do.',
              'YAICON 팀(TDiG)에서 기준을 17가지 기하 지표로 넓혔고, 지금은 마지막 층들이 하는 일을 연구하고 있습니다.')),
        ],
        kpis=[
            ('94.6%', ('of the splice-site effect kept on an unseen chromosome', '처음 보는 염색체에서 유지된 스플라이스 효과'),
             ('calibrated on chr22 → tested on chr17', '22번 염색체로 보정 → 17번 염색체로 시험')),
            ('≈ 2 layers', ('earlier settling at splice sites than in introns', '인트론보다 먼저 정착하는 스플라이스 자리'),
             ('Evo 2 7B · 32 layers · no retraining', 'Evo 2 7B · 32층 · 재학습 없음')),
            ('Oral', ('ICML 2026 GenBio Workshop', 'ICML 2026 GenBio 워크숍'),
             ('workshop paper · bioRxiv preprint', '워크숍 논문 · bioRxiv 프리프린트')),
        ],
        scope=('A workshop paper, not the main conference. The team follow-up TDiG (17 measures, ρ = 0.989 across chromosomes) is reported as 1st prize at the 8th YAICON by the team repository.',
               '메인 컨퍼런스가 아닌 워크숍 논문입니다. 팀 후속 연구 TDiG(17개 지표, 염색체 간 ρ = 0.989)는 팀 저장소 기준 제8회 YAICON 1등입니다.'),
        vision=('A DNA model trained only to predict the next base settles on splice sites about two layers earlier than on introns — grammar that nature wrote, found inside a model. That is the kind of real task I want to work on: reading the genome’s rules through models. Next, I want to see how the last layers turn that grammar into a prediction.',
                '다음 염기만 맞히도록 학습한 DNA 모델이 인트론보다 스플라이스 부위를 약 두 층 먼저 이해하고 있었습니다. 사람이 정한 규칙이 아니라 자연이 쓴 문법을 모델 안에서 찾은 셈입니다. 제가 하고 싶은 일은 이렇게 모델을 통해 유전체의 규칙을 읽어 내는 진짜 과제입니다. 다음으로는 마지막 층들이 그 문법을 어떻게 예측으로 바꾸는지 밝히고 싶습니다.'),
        gh=('01_Medical/GDTR', ('Full research program on GitHub', 'GitHub에서 전체 연구 보기')),
        links=[
            ('paper', 'https://openreview.net/forum?id=Z9h1jiPbus', ('OpenReview', 'OpenReview')),
            ('paper', 'https://www.biorxiv.org/content/10.64898/2026.07.14.738370v1', ('bioRxiv', 'bioRxiv')),
            ('code', 'https://github.com/YAICON-8th-Think-Deep-in-Genome/TDiG', ('Team code (TDiG)', '팀 코드 (TDiG)')),
            ('gh', gh('02_Paper/GDTR'), ('Paper page', '논문 페이지')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- VCC
    dict(
        slug='vcc2026', dom='cell', icon='cell', short='Virtual Cell Challenge 2026',
        kicker=('RNA · Cell · Perturbation · 2026', 'RNA · 세포 · Perturbation · 2026'),
        title=('Predicting how an unseen cell responds to a gene knockdown', '처음 보는 세포가 유전자 억제에 어떻게 반응할지 예측하기'),
        lede=('Arc Institute’s Virtual Cell Challenge 2026, with a six-person team I lead.',
              'Arc Institute의 Virtual Cell Challenge 2026에 제가 이끄는 6인 팀으로 참가하고 있습니다.'),
        card_q=('Predict single-cell responses to gene knockdowns in cell lines the model has never seen.',
                '한 번도 보지 못한 세포주에서 유전자를 억제했을 때 세포 하나하나의 반응을 예측합니다.'),
        card_v='0.5794', card_l=('proxy score on a held-out cell line (no change: 0.5102)', '보지 않은 세포주의 대리 점수 (변화 없음: 0.5102)'),
        outcome=('Arc Institute challenge · final test Oct 2026', 'Arc Institute 챌린지 · 2026년 10월 최종 평가'), status='live',
        badge=('Arc Institute challenge', 'Arc Institute 챌린지'),
        role=('Team Lead · 6-member team', '팀장 · 6인 팀'),
        period=('Aug 2026 – ongoing', '2026.08 – 진행 중'),
        team=('<b>Jiheon Kang (lead)</b>, Minseok Kim, Yumin Jung, Seojin Kim, Seoyeon Kim, Donghyun Lee · YAI Functional Genomics',
              '<b>강지헌(팀장)</b>, 김민석, 정유민, 김서진, 김서연, 이동현 · YAI Functional Genomics'),
        glance=dict(
            topic=('Switch off one gene and the whole cell shifts a little. Such experiments exist at scale for only a few cell lines; a “virtual cell” could predict new ones before anyone runs them.',
                   '유전자 하나를 끄면 세포 전체의 발현이 조금씩 바뀝니다. 이런 실험은 일부 세포주에서만 대규모로 측정돼 있어서, 새 세포주의 반응을 미리 예측하는 “가상 세포”가 필요합니다.'),
            did=('As team lead, built a training-free pipeline that turns control cells into a full submission — <b>400 cells × 18,533 genes</b> per knockdown — plus a leakage-controlled benchmark to test ideas honestly.',
                 '팀장으로서 대조군 세포만으로 제출 파일 전체(억제마다 <b>세포 400개 × 유전자 18,533개</b>)를 만드는 학습 없는 파이프라인과, 아이디어를 공정하게 검증하는 누출 방지 벤치마크를 만들었습니다.'),
            result=('Borrowing effects already measured in similar cell lines beat “no change” (<b>0.5794 vs 0.5102</b> on a public proxy test); large frozen cell encoders added little.',
                    '비슷한 세포주에서 이미 측정된 효과를 빌려 오는 방법이 “변화 없음”보다 좋았고(공개 대리 시험 <b>0.5794 vs 0.5102</b>), 큰 세포 인코더는 크게 보탬이 되지 않았습니다.'),
        ),
        question=[
            ('In a Perturb-seq experiment, one gene is silenced with CRISPRi and hundreds of single cells are sequenced. The 2026 challenge gives teams only unperturbed control cells from three unseen cancer cell lines and 300 target genes — no training data from those lines — and asks what the knocked-down cells will look like.',
             'Perturb-seq 실험에서는 CRISPRi로 유전자 하나를 끄고 수백 개의 단일 세포를 시퀀싱합니다. 2026 챌린지는 처음 보는 암 세포주 3개의 대조군 세포와 표적 유전자 300개만 주고, 해당 세포주의 학습 데이터 없이 유전자를 억제한 세포가 어떻게 보일지 예측하라고 합니다.'),
        ],
        steps=[
            (('Read the context', '맥락 읽기'),
             ('Describe the new cell line from its control cells — raw profiles, PCA or frozen foundation-model embeddings.',
              '대조군 세포로 새 세포주를 표현합니다. 원본 발현, PCA, 고정된 파운데이션 모델 임베딩을 비교했습니다.')),
            (('Transfer known effects', '알려진 효과 옮기기'),
             ('Borrow knockdown effects measured in the most similar reference cell lines.',
              '가장 비슷한 참조 세포주에서 측정된 억제 효과를 빌려 옵니다.')),
            (('Generate the cells', '세포 생성'),
             ('Turn predicted effects into 400 realistic cells per target, ready to submit.',
              '예측한 효과를 표적마다 현실적인 세포 400개로 바꿔 바로 제출할 수 있게 만듭니다.')),
            (('Control evaluation leakage', '평가 누출을 통제하는 검증'),
             ('Score every idea on a shadow benchmark built from public data, with the held-out answers sealed.',
              '공개 데이터로 만든 섀도 벤치마크에서 정답을 봉인한 채 아이디어를 평가합니다.')),
        ],
        kpis=[
            ('0.5794', ('proxy score (PDS) on an unseen cell line', '보지 않은 세포주에서 대리 점수(PDS)'),
             ('“no change” scores 0.5102', '“변화 없음”은 0.5102')),
            ('18,533 × 400', ('genes × cells predicted per knockdown', '억제마다 예측하는 유전자 × 세포'),
             ('training-free, submission-ready', '학습 없이 바로 제출 가능')),
            ('6', ('people in the team I lead', '제가 이끄는 팀 인원'),
             ('each exploring a different route', '팀원마다 다른 방법을 탐색')),
        ],
        scope=('A public-proxy result (Jiang24 IFNG, BxPC3 held out), not an official leaderboard score. The challenge is still running.',
               '공개 데이터로 만든 대리 시험 결과(Jiang24 IFNG, BxPC3 제외)이며 공식 리더보드 점수가 아닙니다. 챌린지는 아직 진행 중입니다.'),
        vision=('How a cell responds to losing a gene is decided by nature, not by a benchmark designer. Our results show that today’s cell embeddings capture only part of those rules — I want to build representations, and benchmarks, that capture more of them.',
                '유전자를 잃은 세포가 어떻게 반응할지는 벤치마크 설계자가 아니라 자연이 정합니다. 우리 결과는 지금의 세포 임베딩이 그 규칙의 일부만 담고 있음을 보여 줍니다. 그 규칙을 더 많이 담는 표현과 벤치마크를 만들고 싶습니다.'),
        gh=('01_Medical/VCC_2026', ('Pipeline and experiments on GitHub', 'GitHub에서 파이프라인과 실험 보기')),
        links=[
            ('code', gh('01_Medical/VCC_2026/experiments'), ('Experiment records', '개별 실험 기록')),
            ('site', 'https://virtualcellchallenge.org/', ('Challenge site', '챌린지 사이트')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- CAFA 6
    dict(
        slug='cafa6', dom='protein', icon='protein', short='CAFA 6',
        kicker=('Protein · Function prediction · 2026', '단백질 · 기능 예측 · 2026'),
        title=('Reading a protein’s job from its sequence', '서열만 보고 단백질이 하는 일 알아맞히기'),
        lede=('An international protein-function prediction challenge on Kaggle — our five-person team won a bronze medal.',
              'Kaggle에서 열린 국제 단백질 기능 예측 대회로, 5인 팀이 동메달을 받았습니다.'),
        card_q=('Which of ~26,000 functions does a protein carry? Predict it from the amino-acid sequence alone.',
                '단백질이 약 26,000개 기능 중 무엇을 가졌는지, 아미노산 서열만으로 예측합니다.'),
        card_v='Bronze', card_v_ko='동메달', card_l=('medal · CAFA 6 on Kaggle', 'Kaggle CAFA 6'),
        outcome=('Bronze Medal · international challenge', '동메달 · 국제 대회'), status='done',
        role=('Team member · ProtT5 branch', '팀원 · ProtT5 담당'),
        period=('Jan – Feb 2026', '2026.01 – 02'),
        team=('Yoonjin Cho (Team Lead), <b>Jiheon Kang</b>, Minseon Koo, Subin Park, Yumin Jung',
              '조윤진(팀장), <b>강지헌</b>, 구민선, 박수빈, 정유민'),
        glance=dict(
            topic=('Protein sequences are cheap to read, but lab tests of what each protein does are slow — most known proteins have no confirmed function.',
                   '단백질 서열은 쉽게 얻지만, 각 단백질이 무슨 일을 하는지 실험으로 확인하는 데는 오래 걸립니다. 그래서 알려진 단백질 대부분은 기능이 확인되지 않았습니다.'),
            did=('In a five-person team, took the <b>ProtT5 branch</b>: a protein language model fine-tuned to score Gene Ontology functions, alongside teammates’ ESM-C and JEPA routes.',
                 '5인 팀에서 <b>ProtT5 갈래</b>를 맡았습니다. 단백질 언어모델을 미세조정해 Gene Ontology 기능마다 점수를 매기는 방법으로, 팀원들의 ESM-C·JEPA 방법과 함께 탐색했습니다.'),
            result=('The team won a <b>bronze medal</b>, learning from 82,404 labelled proteins and predicting for a 224,309-protein test set.',
                    '라벨이 있는 단백질 82,404개로 학습하고 224,309개 단백질에 예측해 <b>동메달</b>을 받았습니다.'),
        ),
        question=[
            ('CAFA is a prospective challenge: predictions are judged against functions discovered <em>after</em> the deadline. Functions come from the Gene Ontology — a tree of about 26,000 terms such as “binding” or “nucleus” — and rare, specific terms count more than generic ones.',
             'CAFA는 마감 <em>이후</em>에 새로 밝혀진 기능으로 채점하는 미래 예측형 대회입니다. 기능은 “결합”, “핵”처럼 약 26,000개 용어로 이뤄진 Gene Ontology 트리로 표현하며, 드물고 구체적인 용어일수록 점수 비중이 큽니다.'),
        ],
        steps=[
            (('Understand the data', '데이터 이해'),
             ('82,404 training proteins and 26,125 function terms — most terms label only a handful of proteins.',
              '학습 단백질 82,404개, 기능 용어 26,125개. 대부분의 용어는 소수의 단백질에만 붙어 있습니다.')),
            (('Split the routes', '방법 나누기'),
             ('Each member took one approach: GO retrieval, ESM-C embeddings, ProtT5 (mine) and JEPA pre-training.',
              '팀원마다 한 갈래씩 맡았습니다. GO 검색, ESM-C 임베딩, ProtT5(제 담당), JEPA 사전학습입니다.')),
            (('Respect the hierarchy', '계층 지키기'),
             ('Propagate predictions up the ontology tree so that every answer stays consistent.',
              '예측을 온톨로지 트리 위쪽으로 전파해 답이 서로 모순되지 않게 합니다.')),
        ],
        kpis=[
            ('Bronze', ('medal in CAFA 6 (Kaggle)', 'CAFA 6 (Kaggle)'), ('team result', '팀 성과')),
            ('82,404', ('labelled proteins learned from', '학습에 쓴 라벨 단백질'), ('UniProt / Swiss-Prot', 'UniProt / Swiss-Prot')),
            ('224,309', ('proteins predicted', '예측한 단백질'), ('test superset; scored on later lab results', '테스트 상위집합 · 이후 실험 결과로 채점')),
        ],
        kpi_ko={'Bronze': '동메달'},
        scope=None,
        vision=('Every label in CAFA is a function that nature gave a protein and an experiment confirmed. Learning those rules from sequence helps decide which proteins get studied next — and CAFA taught me that how a task is scored, with rare, specific functions weighing more, shapes what a model learns.',
                'CAFA의 정답 하나하나는 자연이 단백질에 준 기능을 실험으로 확인한 것입니다. 서열에서 그 규칙을 배우는 모델은 다음에 어떤 단백질을 연구할지 정하는 데 쓰입니다. 드물고 구체적인 기능에 더 큰 비중을 두는 평가 방식이 모델이 배우는 것을 바꾼다는 점도 배웠습니다.'),
        gh=('01_Medical/CAFA6', ('Pipelines and notes on GitHub', 'GitHub에서 파이프라인과 노트 보기')),
        links=[
            ('code', 'https://github.com/heoneyzi/CAFA6', ('Code (fork)', '코드 (fork)')),
            ('site', 'https://www.kaggle.com/competitions/cafa-6-protein-function-prediction', ('Competition', '대회 페이지')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- PhenoFocus
    dict(
        slug='phenofocus', dom='drug', icon='pill', short='PhenoFocus',
        kicker=('Drug discovery · Cell images · 2026', '신약 개발 · 세포 이미지 · 2026'),
        title=('Same biology, different skeleton', '같은 작용, 다른 골격'),
        lede=('AI-driven drug discovery from cell images — advanced to the main round of the 2026 Research-Idea Commercialization Challenge.',
              '세포 이미지로 하는 AI 신약 개발 — 2026 연구 아이디어 사업화 챌린지 본선에 진출했습니다.'),
        card_q=('One compound that works goes in; chemically new candidates with the same effect on cells come out.',
                '효과가 확인된 화합물 하나를 넣으면, 세포에 같은 효과를 내지만 구조가 다른 후보를 찾아 줍니다.'),
        card_v='6.2×', card_l=('more same-mechanism hits in the top 5', '상위 5개 안의 같은 작용 후보 농축'),
        outcome=('Main round · 2026 Research-Idea Commercialization Challenge', '본선 진출 · 2026 연구 아이디어 사업화 챌린지'), status='live',
        badge=('Competition main round', '대회 본선 진출'),
        role=('Team Lead · 4-member team', '팀장 · 4인 팀'),
        period=('2026 – ongoing', '2026 – 진행 중'),
        team=('<b>Jiheon Kang (Team Lead)</b>, Jaeyoung Ha, Jungyoon Han, Hyunjun Hwang',
              '<b>Jiheon Kang(팀장)</b>, Jaeyoung Ha, Jungyoon Han, Hyunjun Hwang'),
        glance=dict(
            topic=('Drug programs stall when every promising compound shares one chemical skeleton — a single toxicity or patent problem stops them all.',
                   '유망한 화합물이 모두 같은 화학 골격을 공유하면, 독성이나 특허 문제 하나로 신약 개발 전체가 멈춥니다.'),
            did=('As team lead, built a search layer on a model that links chemical structure to how compounds change cell images, and tested whether it finds <b>same-mechanism compounds with different skeletons</b>.',
                 '팀장으로서 화학 구조와 “화합물이 세포 이미지를 어떻게 바꾸는지”를 연결한 모델 위에 검색 기능을 만들고, <b>작용은 같고 골격은 다른 화합물</b>을 찾는지 시험했습니다.'),
            result=('From one HDAC-inhibitor hit, both other HDAC inhibitors in a 31-compound library landed in the <b>top 5</b> — one from a different chemical class.',
                    'HDAC 억제제 하나로 검색하자, 31개 화합물 중 나머지 HDAC 억제제 2개가 모두 <b>상위 5위</b> 안에 들었고, 그중 하나는 화학 계열이 달랐습니다.'),
        ),
        question=[
            ('Cell Painting photographs stained cells, so every compound leaves a visual fingerprint of what it does. A model that has learned which compounds make cells look alike can be asked for compounds that act the same way but look different chemically — scaffold hopping in software instead of at the bench.',
             'Cell Painting은 염색한 세포를 촬영해 화합물마다 세포에 남기는 “시각적 지문”을 얻는 실험입니다. 어떤 화합물들이 세포를 비슷하게 바꾸는지 배운 모델이라면, 작용은 같지만 화학 구조는 다른 화합물을 찾아 줄 수 있습니다. 실험실 대신 소프트웨어에서 하는 골격 바꾸기(scaffold hopping)입니다.'),
        ],
        steps=[
            (('Start from one hit', '화합물 하나에서 시작'),
             ('Feed in a single compound that is known to work in cells.', '세포에서 효과가 확인된 화합물 하나를 넣습니다.')),
            (('Search in biology space', '생물학 공간에서 검색'),
             ('Rank a compound library by how similarly the model expects each one to change cells.',
              '모델이 예상하는 세포 변화가 얼마나 비슷한지로 화합물 라이브러리를 정렬합니다.')),
            (('Keep the new skeletons', '새 골격 고르기'),
             ('Check chemical similarity so that candidates are truly different molecules.',
              '화학적 유사도를 확인해 후보가 실제로 다른 분자인지 봅니다.')),
            (('Be honest about scope', '한계까지 기록'),
             ('Benchmark across six mechanisms and write down where it fails.', '6가지 작용 기전으로 벤치마크하고 잘 안 되는 경우도 기록합니다.')),
        ],
        kpis=[
            ('0.97', ('AUROC for finding same-mechanism compounds', '같은 작용 화합물을 찾는 AUROC'),
             ('one query · 31-compound library', '질의 1개 · 화합물 31개')),
            ('6.2×', ('enrichment of same-mechanism hits in the top 5', '상위 5개 안의 같은 작용 후보 농축'),
             ('chemical look-alike search: 3.1×', '화학 구조 유사도 검색은 3.1배')),
            ('0.10', ('chemical similarity of the rank-4 hit to the query', '4위 후보와 질의 화합물의 화학적 유사도'),
             ('an HDAC inhibitor from a different chemical class', '계열이 다른 HDAC 억제제')),
        ],
        scope=('Exploratory: a single query on a small library. Across six mechanisms the average was lower (macro AUROC 0.716), so this is a promising start, not a proof.',
               '탐색적 실험입니다(질의 1개, 작은 라이브러리). 6개 기전 평균은 더 낮았습니다(macro AUROC 0.716). 가능성을 본 첫 단계이지 증명은 아닙니다.'),
        vision=('What a drug does to a cell is a rule of nature we can photograph. If a model learns it, it can suggest molecules a chemist would not have tried. Next, I want to test the image side across different cell lines — the step that makes this useful in a real lab.',
                '약물이 세포에 하는 일은 사진으로 찍을 수 있는 자연의 규칙입니다. 모델이 그 규칙을 배운다면, 화학자가 시도하지 않았을 분자를 제안할 수 있습니다. 다음 단계는 서로 다른 세포주에서 이미지 쪽을 검증해, 실제 실험실에서 쓸 수 있게 만드는 일입니다.'),
        gh=('01_Medical/PhenoFocus', ('Experiments and code on GitHub', 'GitHub에서 실험과 코드 보기')),
        links=[
            ('code', gh('01_Medical/PhenoFocus/experiments'), ('Experiment records', '개별 실험 기록')),
            ('paper', 'https://www.biorxiv.org/content/10.64898/2026.06.10.731476v1', ('PhenoCompass preprint', 'PhenoCompass 프리프린트')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- FTF-VTG
    dict(
        slug='ftf-vtg', dom='ai', icon='film', short='FTF-VTG',
        kicker=('Multimodal AI · Video · 2025', '멀티모달 AI · 영상 · 2025'),
        title=('Finding when a sentence happens in a video — without training', '학습 없이 영상 속 문장이 가리키는 순간 찾기'),
        lede=('First-author paper from the deep daiv. multimodal team I led, accepted at the 2025 IEIE Summer Annual Conference.',
              '제가 이끈 deep daiv. 멀티모달 팀의 연구로, 2025 대한전자공학회 하계종합학술대회에 제1저자로 채택됐습니다.'),
        card_q=('One frozen image–text model scores every frame; simple signal processing finds the moment.',
                '고정된 이미지-텍스트 모델 하나로 프레임마다 점수를 매기고, 간단한 신호 처리로 그 순간을 찾습니다.'),
        card_v='788 MiB', card_l=('GPU memory — a baseline needs 9,537 MiB', 'GPU 메모리 (비교 방법 9,537 MiB)'),
        outcome=('Accepted · 2025 IEIE Summer Annual Conference', '채택 · 2025 대한전자공학회 하계종합학술대회'), status='done',
        badge=('IEIE 2025 · first author', 'IEIE 2025 · 제1저자'),
        role=('First author · Team Lead', '제1저자 · 팀장'),
        period=('Nov 2024 – Summer 2025', '2024.11 – 2025 여름'),
        team=('<b>Jiheon Kang</b>, Suyong Kim, Harim Noh, Heejae Yang · deep daiv. multimodal team',
              '<b>Jiheon Kang</b>, Suyong Kim, Harim Noh, Heejae Yang · deep daiv. 멀티모달 팀'),
        glance=dict(
            topic=('Video search needs the start and end of the moment a sentence describes. Most methods train on costly labels or stack several large models.',
                   '영상 검색에는 문장이 설명하는 장면의 시작과 끝이 필요합니다. 대부분의 방법은 비싼 라벨로 학습하거나 큰 모델을 여러 개 씁니다.'),
            did=('Led the research team and first-authored the paper: score each frame against the sentence with a frozen CLIP model, then turn that similarity curve into a time span.',
                 '연구팀을 이끌고 제1저자로 논문을 썼습니다. 고정된 CLIP 모델로 프레임마다 문장과의 유사도를 구하고, 그 곡선을 시간 구간으로 바꿨습니다.'),
            result=('More accurate than a training-free baseline at about <b>a tenth of the GPU memory</b>: DiDeMo R@1 19.30 vs 15.56, VidSTG mIoU 39.01 vs 24.94.',
                    '학습 없는 비교 방법보다 정확하면서 GPU 메모리는 <b>약 10분의 1</b>이었습니다. DiDeMo R@1 19.30 vs 15.56, VidSTG mIoU 39.01 vs 24.94.'),
        ),
        question=[
            ('When a strong image–text model scores each frame against the query, the score rises as the described event starts and falls as it ends. If the boundaries are visible in that curve, finding the moment becomes a simple, traceable signal-processing problem.',
             '강한 이미지-텍스트 모델로 프레임마다 문장과의 유사도를 매기면, 사건이 시작될 때 점수가 오르고 끝날 때 내려갑니다. 경계가 곡선에 드러난다면, 장면 찾기는 단순하고 추적 가능한 신호 처리 문제가 됩니다.'),
        ],
        steps=[
            (('Score the frames', '프레임 점수 매기기'),
             ('A frozen CLIP model rates every frame against the sentence.', '고정된 CLIP 모델이 프레임마다 문장과의 유사도를 매깁니다.')),
            (('Clean the curve', '곡선 다듬기'),
             ('Smooth the similarity curve and find where it rises and falls.', '유사도 곡선을 부드럽게 만들고 오르내리는 지점을 찾습니다.')),
            (('Pick the moment', '순간 고르기'),
             ('Turn the strongest region into start and end times — no training, no LLM.', '가장 강한 구간을 시작·끝 시각으로 바꿉니다. 학습도 LLM도 쓰지 않습니다.')),
        ],
        kpis=[
            ('19.30', ('DiDeMo R@1 (IoU ≥ 0.5)', 'DiDeMo R@1 (IoU ≥ 0.5)'), ('baseline: 15.56', '비교 방법: 15.56')),
            ('39.01', ('VidSTG mIoU', 'VidSTG mIoU'), ('baseline: 24.94', '비교 방법: 24.94')),
            ('788 MiB', ('GPU memory', 'GPU 메모리'), ('baseline: 9,537 MiB', '비교 방법: 9,537 MiB')),
        ],
        scope=('Numbers as reported in the paper’s result notes; the baseline is TFVTG run without its LLM stage.',
               '수치는 논문 결과 노트 기준이며, 비교 방법은 LLM 단계를 뺀 TFVTG입니다.'),
        vision=('Frozen models already know more than we use. Reading them carefully — here, frame by frame — replaced heavy training. The same instinct now drives my work on DNA models, where what a model has learned can be one of nature’s rules.',
                '고정된 모델은 우리가 쓰는 것보다 많은 것을 이미 알고 있습니다. 여기서는 프레임 단위로 꼼꼼히 읽는 것만으로 무거운 학습을 대신했습니다. 같은 생각이 지금 DNA 모델 연구로 이어지고 있습니다. 거기서는 모델이 배운 것이 곧 자연의 규칙일 수 있습니다.'),
        gh=('02_Paper/FTFVTG', ('Paper page and code on GitHub', 'GitHub에서 논문 페이지와 코드 보기')),
        links=[
            ('code', 'https://github.com/heoneyzi/Frame_based_Training_Free-Video_Temporal_Grounding', ('Original code', '원본 코드')),
            ('paper', 'https://github.com/heoneyzi/Paper/blob/main/FTFVTG/Frame-Level%20Understanding%20for%20Lightweight%20and%20Explainable%20Video%20Temporal%20Grounding.pdf', ('PDF', 'PDF')),
            ('gh', gh('04_Deep_Daiv/Project/Multimodal'), ('How the project started', '프로젝트가 시작된 과정')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- Bi-CoT
    dict(
        slug='bi-cot', dom='ai', icon='route', short='Bi-CoT',
        kicker=('Reasoning · Explainable QA · 2025', '추론 · 설명 가능한 QA · 2025'),
        title=('An AI that shows its reasoning — and checks it backwards', '추론 과정을 보여 주고, 거꾸로 검증하는 AI'),
        lede=('First-author paper accepted at the 6th Korea Artificial Intelligence Conference.',
              '제6회 한국인공지능학술대회에 제1저자로 채택된 논문입니다.'),
        card_q=('Multi-hop questions answered one step at a time, with every step re-checked in reverse.',
                '여러 단계를 거쳐야 하는 질문을 한 단계씩 풀고, 각 단계를 거꾸로 다시 확인합니다.'),
        card_v='24.2 → 42.8', card_l=('HotpotQA exact match vs a retrieve-and-read baseline', 'HotpotQA 정답 일치율, 기본 방법 대비'),
        outcome=('Accepted · 6th Korea AI Conference', '채택 · 제6회 한국인공지능학술대회'), status='done',
        badge=('KAIC 2025 · first author', 'KAIC 2025 · 제1저자'),
        role=('First author', '제1저자'),
        period=('2025', '2025'),
        team=('<b>Jiheon Kang</b>, Suhwan Jung', '<b>Jiheon Kang</b>, Suhwan Jung'),
        glance=dict(
            topic=('Questions such as “what office did the lead actress of film X hold?” need several facts in a row. If an early step is wrong, the error quietly spreads — and most systems show only the final answer.',
                   '“영화 X의 주연 배우가 맡았던 공직은?” 같은 질문은 여러 사실을 차례로 찾아야 합니다. 앞 단계가 틀리면 오류가 조용히 퍼지는데, 대부분의 시스템은 최종 답만 보여 줍니다.'),
            did=('Designed an inference-only pipeline: split the question into sub-questions, answer each with frozen models, check every step against its evidence, then <b>verify the chain in reverse</b>.',
                 '학습 없이 추론만 바꾸는 파이프라인을 설계했습니다. 질문을 하위 질문으로 나누고, 고정된 모델로 하나씩 답하고, 단계마다 근거와 대조한 뒤, <b>거꾸로 전체를 검증</b>합니다.'),
            result=('On HotpotQA, exact match rose from <b>24.16 to 42.77</b> and F1 from 33.15 to 55.40 over a retrieve-and-read baseline — with no parameters trained.',
                    'HotpotQA에서 정답 일치율(EM)은 <b>24.16 → 42.77</b>, F1은 33.15 → 55.40으로 올랐습니다. 학습한 파라미터는 없습니다.'),
        ),
        question=[
            ('Strong question-answering systems are usually fine-tuned on the benchmark and return only an answer, so when they fail it is hard to see which step went wrong. Bi-CoT keeps every model frozen and changes only how inference is run: it records each step and adds a backward pass that can catch mistakes.',
             '성능이 좋은 질의응답 시스템은 보통 벤치마크에 맞춰 미세조정되고 최종 답만 내놓기 때문에, 틀렸을 때 어느 단계가 잘못됐는지 알기 어렵습니다. Bi-CoT는 모든 모델을 고정한 채 추론 방식만 바꿉니다. 모든 단계를 기록하고, 실수를 잡아낼 수 있는 역방향 검증을 더합니다.'),
        ],
        steps=[
            (('Decompose', '분해'), ('Split the question into sub-questions that depend on each other.', '질문을 서로 이어진 하위 질문으로 나눕니다.')),
            (('Answer with evidence', '근거와 함께 답하기'),
             ('A frozen retriever and reader answer each step, and each answer is checked against its passage.',
              '고정된 검색기와 독해 모델이 단계마다 답하고, 답을 근거 문단과 대조합니다.')),
            (('Verify backwards', '거꾸로 검증'),
             ('Re-check the whole chain from the answer back to the question before finalising.',
              '답에서 질문 쪽으로 전체 연결을 다시 확인한 뒤 최종 답을 냅니다.')),
        ],
        kpis=[
            ('42.77', ('exact match on HotpotQA', 'HotpotQA 정답 일치율(EM)'), ('baseline: 24.16', '기본 방법: 24.16')),
            ('55.40', ('F1 on HotpotQA', 'HotpotQA F1'), ('baseline: 33.15', '기본 방법: 33.15')),
            ('0', ('parameters trained', '학습한 파라미터'), ('inference only · frozen models', '추론만 변경 · 고정 모델')),
        ],
        scope=('Numbers as reported in the paper draft (HotpotQA, full-wiki setting).',
               '수치는 논문 원고 기준입니다(HotpotQA full-wiki 설정).'),
        vision=('Multi-hop QA is a task people designed. The habit it taught me — show each step and check it — is what I now bring to questions nature designed.',
                '멀티홉 질의응답은 사람이 설계한 과제입니다. 이 과제에서 익힌 습관, 즉 각 단계를 보여 주고 확인하는 습관을 지금은 자연이 설계한 질문에 가져가고 있습니다.'),
        gh=('02_Paper/Bi-CoT', ('Paper page and code on GitHub', 'GitHub에서 논문 페이지와 코드 보기')),
        links=[
            ('code', 'https://github.com/heoneyzi/Bi-CoT', ('Original code', '원본 코드')),
            ('paper', 'https://github.com/heoneyzi/Paper/blob/main/Bi-CoT/Plug-and-Play%20Bi-CoT%20-%20Self-Aware%20Forward%20Reasoning%20and%20Reverse%20Verification%20for%20Explainable%20Multi-Hop%20QA.pdf', ('PDF', 'PDF')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- GeoFlowAgent
    dict(
        slug='geoflowagent', dom='dna', icon='compass', short='GeoFlowAgent',
        kicker=('AI agents · Clinical variants · 2026', 'AI 에이전트 · 임상 변이 · 2026'),
        title=('An AI agent that plans genomics tool use on a frozen model’s map', '고정된 모델의 지도 위에서 유전체 도구 사용을 계획하는 AI 에이전트'),
        lede=('Independent research on AI agents for clinical variant interpretation, completed in September 2026.',
              '임상 변이 해석을 위한 AI 에이전트에 관한 개인 연구로, 2026년 9월에 마무리했습니다.'),
        card_q=('Can an agent plan a multi-step variant analysis inside a frozen model’s embedding space?',
                '고정된 모델의 임베딩 공간 안에서 에이전트가 여러 단계의 변이 분석을 계획할 수 있을까?'),
        card_v='0.40 vs 0.12', card_l=('goal completion: replan vs one-shot', '목표 달성률: 재계획 vs 한 번에 계획'),
        outcome=('Independent research · completed', '개인 연구 · 완료'), status='done',
        role=('Independent researcher', '개인 연구자'),
        period=('Sep 2026', '2026.09'),
        team=('Solo project', '개인 프로젝트'),
        glance=dict(
            topic=('AI agents are starting to run genomics workflows: check how common a variant is, run predictors, look up clinical records, then decide. Which tool call brings them closer to the answer?',
                   'AI 에이전트가 유전체 분석을 수행하기 시작했습니다. 변이가 얼마나 흔한지 확인하고, 예측 도구를 돌리고, 임상 기록을 찾은 뒤 판단하죠. 어떤 도구 호출이 답에 더 가까워지게 할까요?'),
            did=('Kept biomedical language models frozen and used their embedding space as the planner’s map; built a synthetic benchmark evaluated once on a held-out test, and tasks derived from ClinGen expert records.',
                 '생의학 언어모델을 고정한 채 그 임베딩 공간을 계획용 지도로 썼습니다. 테스트를 한 번만 평가한 합성 벤치마크와, ClinGen 전문가 기록으로 만든 과제를 구축했습니다.'),
            result=('Act, observe, replan clearly beat planning everything at once (<b>0.40 vs 0.12</b> on the one-time test, 0.60 vs 0.12 on ClinGen tasks). The “best” distance measure changed with how the space is read.',
                    '실행하고, 결과를 보고, 다시 계획하는 방식이 한 번에 계획하는 방식보다 확실히 좋았습니다(한 번 평가한 테스트 <b>0.40 vs 0.12</b>, ClinGen 과제 0.60 vs 0.12). “최고”의 거리 척도는 공간을 읽는 방식에 따라 달라졌습니다.'),
        ),
        question=[
            ('ClinGen publishes which evidence experts applied to a variant — and which they checked and rejected. That makes a realistic testbed: some tool calls cost time and return nothing useful, so planning really matters. The idea builds on FlowAgent’s latent flow-matching planning.',
             'ClinGen은 전문가가 변이에 적용한 근거뿐 아니라, 확인했지만 채택하지 않은 근거까지 공개합니다. 어떤 도구 호출은 시간만 들고 쓸모가 없기 때문에, 계획이 정말 중요한 현실적인 실험장이 됩니다. 아이디어는 FlowAgent의 잠재 공간 flow-matching 계획에서 출발했습니다.'),
        ],
        steps=[
            (('Freeze the encoder', '인코더 고정'),
             ('Use a pretrained biomedical model’s embeddings as the map and train only a small head.', '사전학습된 생의학 모델의 임베딩을 지도로 쓰고, 작은 헤드만 학습합니다.')),
            (('Plan whole routes', '경로 전체 계획'),
             ('A flow-matching planner proposes complete tool-use plans toward the goal.', 'flow-matching 플래너가 목표까지의 도구 사용 계획을 통째로 제안합니다.')),
            (('Seal the test', '테스트 봉인'),
             ('Fix the rules in advance and open the test split only once.', '규칙을 미리 정하고, 테스트 세트는 단 한 번만 엽니다.')),
            (('Claim only what holds', '유지되는 것만 주장'),
             ('Keep negative results, and call a result “unresolved” when its confidence interval includes zero.', '부정적인 결과도 남기고, 신뢰구간이 0을 포함하면 “미결”로 적습니다.')),
        ],
        kpis=[
            ('0.40 vs 0.12', ('goal completion: replan vs one-shot', '목표 달성률: 재계획 vs 단발 계획'),
             ('one-time synthetic test · 48 tasks × 3 seeds', '한 번 평가한 합성 테스트 · 과제 48개 × 시드 3개')),
            ('0.60 vs 0.12', ('the same comparison on ClinGen-derived tasks', 'ClinGen 기반 과제에서 같은 비교'),
             ('ClinGen-derived development split · 584 tasks', 'ClinGen 기반 개발 세트 · 과제 584개')),
            ('0.00', ('for a blind replanner with the same compute', '같은 계산량의 “보지 않는” 재계획'),
             ('observing, not extra compute, drives the gain', '이득은 계산량이 아니라 관찰에서 나옴')),
        ],
        scope=('Independent study. Synthetic numbers come from its one-time test; ClinGen numbers from the 584-task development split.',
               '개인 연구입니다. 합성 벤치마크 수치는 한 번 평가한 테스트, ClinGen 수치는 과제 584개 개발 세트의 결과입니다.'),
        vision=('Interpreting a variant is a real task: the evidence comes from nature, gathered in expert records, and many lookups come back empty. The agent did best when it looked at each result before choosing the next step — the way a scientist works. I want agents that explore biology like that.',
                '변이 해석은 진짜 과제입니다. 근거는 자연에서 오고 전문가 기록에 모여 있으며, 찾아봐도 쓸 근거가 없는 경우가 많습니다. 에이전트는 결과를 하나씩 확인하고 다음 단계를 정할 때 가장 잘했습니다. 과학자가 일하는 방식과 같습니다. 저는 이렇게 생물학을 탐색하는 에이전트를 만들고 싶습니다.'),
        gh=('01_Medical/GeoFlowAgent', ('Experiments and code on GitHub', 'GitHub에서 실험과 코드 보기')),
        links=[],
    ),
    # ------------------------------------------------------------------------------------------- BU-Net
    dict(
        slug='bu-net', dom='clinic', icon='pulse', short='Lightweight BU-Net',
        kicker=('Clinic · Medical imaging · 2024', '임상 · 의료 영상 · 2024'),
        title=('Brain-tumour segmentation on a student GPU budget', '학생 GPU로 하는 뇌종양 분할'),
        lede=('Medical AI team project at deep daiv., presented at the 8th deep daiv. Open Seminar.',
              'deep daiv. 의료 AI 팀 프로젝트로, 제8회 deep daiv. 오픈 세미나에서 발표했습니다.'),
        card_q=('Keep BU-Net’s wide-context ideas, but slim the model enough to train on limited hardware.',
                'BU-Net의 넓은 맥락 아이디어는 살리고, 제한된 장비에서도 학습할 수 있게 모델을 줄입니다.'),
        card_v='3', card_l=('models: U-Net · U-Net + WC · Simplified BU-Net', '모델: U-Net · U-Net + WC · 단순화 BU-Net'),
        outcome=('Presented · 8th deep daiv. Open Seminar', '발표 · 제8회 deep daiv. 오픈 세미나'), status='done',
        role=('Team Lead · 3-member team', '팀장 · 3인 팀'),
        period=('Spring 2024', '2024 봄'),
        team=('<b>Jiheon Kang (Team Lead)</b>, Boyoung Kwon, Jaeryeong Hwang · deep daiv. Medical AI',
              '<b>강지헌(팀장)</b>, 권보영, 황재령 · deep daiv. 의료 AI 팀'),
        glance=dict(
            topic=('Radiologists outline brain tumours by hand on four kinds of MRI. Tumours are tiny next to the brain, so a model that predicts “no tumour” everywhere can still look accurate.',
                   '영상의학과 의사는 네 종류의 MRI에서 뇌종양 경계를 직접 그립니다. 종양은 뇌에 비해 아주 작아서, 모든 곳을 “종양 없음”으로 예측하는 모델도 정확해 보일 수 있습니다.'),
            did=('Led a three-person team that studied BU-Net and built U-Net, U-Net + wide context and a simplified BU-Net on BraTS 2018 MRI slices; in 2026 I restored the archive with a comparison viewer and tests.',
                 '3인 팀을 이끌며 BU-Net을 공부하고, BraTS 2018 MRI 슬라이스로 U-Net, U-Net + WC, 단순화 BU-Net을 구현했습니다. 2026년에는 비교 뷰어와 테스트를 붙여 아카이브를 복원했습니다.'),
            result=('Presented a side-by-side comparison of predicted tumour masks at the open seminar. No Dice score was recorded at the time, so none is claimed.',
                    '오픈 세미나에서 모델별 종양 마스크를 나란히 비교해 발표했습니다. 당시 Dice 점수를 기록하지 않아 수치는 주장하지 않습니다.'),
        ),
        question=[
            ('BU-Net adds two ideas to the classic U-Net: wide-context blocks that see far across the image cheaply, and richer skip connections. Could those ideas survive when the model is simplified for student hardware?',
             'BU-Net은 기본 U-Net에 두 가지 아이디어를 더합니다. 이미지를 넓게 보는 wide-context 블록과 더 풍부한 skip 연결입니다. 학생용 장비에 맞게 모델을 단순화해도 이 아이디어가 살아남을까요?'),
        ],
        steps=[
            (('Read the papers', '논문 리뷰'), ('Reviewed BU-Net and a chest X-ray preprocessing paper.', 'BU-Net과 흉부 X-ray 전처리 논문을 리뷰했습니다.')),
            (('Build three models', '모델 3개 구현'), ('U-Net, U-Net + wide context and a simplified BU-Net in PyTorch.', 'PyTorch로 U-Net, U-Net + WC, 단순화 BU-Net을 만들었습니다.')),
            (('Compare and present', '비교와 발표'), ('Showed the predicted tumour masks side by side at the seminar.', '예측한 종양 마스크를 나란히 비교해 세미나에서 발표했습니다.')),
            (('Restore the archive (2026)', '아카이브 복원 (2026)'), ('Recovered the notebooks and added a viewer, tests and reproduction notes.', '노트북을 복원하고 뷰어, 테스트, 재현 안내를 더했습니다.')),
        ],
        kpis=[
            ('3', ('segmentation models built and compared', '구현하고 비교한 분할 모델'), ('qualitative comparison', '정성 비교')),
            ('4', ('classes per pixel', '픽셀마다 나누는 클래스'), ('background · core · edema · enhancing', '배경 · 중심부 · 부종 · 조영 증강')),
            ('2024 → 2026', ('archive restored with a viewer and tests', '뷰어와 테스트를 갖춘 아카이브 복원'), ('reproducible for others', '다른 사람도 재현 가능')),
        ],
        scope=('“Lightweight” means simplified relative to the full BU-Net drafts; the simplified BU-Net is still larger than a plain U-Net.',
               '“경량”은 원래 BU-Net 초안보다 단순화했다는 뜻입니다. 단순화 BU-Net도 기본 U-Net보다는 큽니다.'),
        vision=('My first medical project: the answers came from real patients’ scans rather than from a task someone designed — a first taste of the real tasks I now look for.',
                '저의 첫 의료 프로젝트였습니다. 정답이 누군가 설계한 과제가 아니라 실제 환자의 영상에서 나왔고, 지금 제가 찾는 진짜 과제를 처음 경험한 프로젝트였습니다.'),
        gh=('01_Medical/Bu-net', ('Models, notes and viewer on GitHub', 'GitHub에서 모델, 노트, 뷰어 보기')),
        links=[
            ('code', 'https://github.com/heoneyzi/BU-Net_Pytorch_Implementation', ('Team code (fork)', '팀 코드 (fork)')),
            ('code', 'https://github.com/heoneyzi/reinforcing_material', ('Research archive', '연구 아카이브')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- Persona chatbot
    dict(
        slug='persona-chatbot', dom='ai', icon='chat', short='Persona chatbot',
        kicker=('LLM · RAG · Prompting · 2023–24', 'LLM · RAG · 프롬프트 · 2023–24'),
        title=('Chatting with a character through RAG and prompts', 'RAG와 프롬프트로 캐릭터와 대화하기'),
        lede=('deep daiv. NLP team project: a Streamlit chat that speaks as an actor or a drama character, grounded in their wiki page through RAG.',
              'deep daiv. NLP 팀 프로젝트 — 인물의 위키 문서를 RAG로 검색해, 배우나 드라마 캐릭터처럼 말하는 Streamlit 채팅.'),
        card_q=('GPT-4 speaks as an actor or drama character: RAG over the person’s wiki page for the facts, one reusable prompt for the voice.',
                'GPT-4가 배우나 드라마 캐릭터처럼 말합니다. 사실은 인물 위키 문서의 RAG 검색으로, 말투는 재사용 가능한 프롬프트 하나로.'),
        card_v='RAG', card_l=('retrieval over each person’s wiki page', '인물 위키 문서를 검색해 답에 활용'),
        outcome=('Demo · final seminar', '데모 · 최종 세미나'), status='done',
        role=('Team Lead · 4-member team', '팀장 · 4인 팀'),
        period=('Nov 2023 – Jan 2024', '2023.11 – 2024.01'),
        team=('강민재 · <b>강지헌 (Team Lead)</b> · 장래영 · 장윤경 · deep daiv. NLP', '강민재 · <b>강지헌(팀장)</b> · 장래영 · 장윤경 · deep daiv. NLP'),
        glance=dict(
            topic=('Fan-chat services depend on the star actually replying, or on a model trained per person. Could a general LLM plus the right context play anyone?',
                   '팬 메시지 서비스는 스타가 직접 답하거나, 사람마다 따로 학습한 모델이 필요합니다. 범용 LLM에 알맞은 맥락만 주면 누구든 연기할 수 있을까요?'),
            did=('Led the team through its RAG design — first fetching the wiki section each question needs, then retrieval over the whole page with the Assistants API — and owned one persona’s prompt: drama lines as examples, first-person speech and rules that kept the character in role.',
                 '팀을 이끌며 RAG를 설계했습니다. 처음에는 질문마다 필요한 위키 섹션을 찾아 넣는 방식, 다음에는 Assistants API로 문서 전체를 검색하는 방식이었습니다. 한 페르소나의 프롬프트도 맡아 드라마 대사를 예시로 넣고, 1인칭 말투를 고정하고, 캐릭터가 역할을 지키게 하는 규칙을 썼습니다.'),
            result=('Retrieval kept the facts grounded — the actor’s persona turned down peaches because of the allergy on his page — while negative examples and injected date, weather and news made replies noticeably more natural (qualitative tests on four personas).',
                    '검색(RAG)은 답을 사실에 묶어 두었습니다. 배우 페르소나는 문서에 적힌 복숭아 알레르기를 근거로 복숭아를 사양했습니다. 부정 예시와 날짜·날씨·뉴스 정보를 넣자 답변이 눈에 띄게 자연스러워졌습니다(4명 페르소나 정성 평가).'),
        ),
        question=[
            ('Retrieval-augmented generation fetches relevant passages from a document — here the person’s profile page — so answers stay grounded in facts. Prompt engineering steers behaviour with instructions and examples. Neither changes the model’s weights, so a new persona costs one document, not one training run.',
             '검색 증강 생성(RAG)은 문서(여기서는 인물의 프로필 페이지)에서 관련 내용을 찾아 넣어 답이 사실에 기반하게 합니다. 프롬프트 엔지니어링은 지시문과 예시로 행동을 조정합니다. 둘 다 모델 가중치를 바꾸지 않으므로, 새 페르소나에는 학습 대신 문서 하나만 있으면 됩니다.'),
        ],
        steps=[
            (('Build retrieval (RAG)', '검색(RAG) 만들기'), ('Start by fetching the wiki section a question needs; when page layouts proved too inconsistent, move to retrieval over the whole page with the Assistants API.', '질문마다 필요한 위키 섹션을 찾아 넣는 방식으로 시작했고, 문서 구조가 사람마다 너무 달라 Assistants API로 문서 전체를 검색하는 방식으로 옮겼습니다.')),
            (('Write one reusable prompt', '재사용 프롬프트 작성'), ('Goal, background, rules, example lines and “false examples”.', '목표, 배경, 규칙, 예시 대사, 그리고 “잘못된 예시”를 담았습니다.')),
            (('Fix what breaks', '깨지는 부분 고치기'), ('Add rules only after watching the character fail — e.g. mixing up the drama and the real world.', '캐릭터가 실제로 실패하는 모습을 보고 규칙을 더했습니다. 예를 들어 드라마 속 세계와 현실을 혼동할 때입니다.')),
            (('Ship a demo', '데모 공개'), ('Serve it as a Streamlit chat for the final seminar.', '최종 세미나에서 Streamlit 채팅으로 시연했습니다.')),
        ],
        kpis=[
            ('4', ('personas tested', '시험한 페르소나'), ('three drama characters and one actor', '드라마 캐릭터 3명과 배우 1명')),
            ('RAG', ('facts retrieved from each person’s wiki page', '인물 위키 문서에서 사실을 검색'), ('two designs: section retrieval, then whole-page retrieval', '두 가지 설계: 섹션 검색 → 문서 전체 검색')),
            ('1 prompt', ('reused across every persona', '모든 페르소나에 재사용'), ('plus one profile document each', '페르소나마다 프로필 문서 1개')),
        ],
        kpi_ko={'1 prompt': '프롬프트 1개'},
        scope=('Evaluated qualitatively on chat transcripts of four personas.', '4명의 페르소나 대화 기록으로 정성 평가했습니다.'),
        vision=('What a model says depends on the context we give it. Retrieval grounded each persona in facts from a real document, and the prompt shaped its voice — an early lesson in steering LLM behaviour, where every rule came from an observed failure.',
                '모델이 하는 말은 우리가 주는 맥락에 달려 있습니다. 검색(RAG)은 페르소나의 답을 실제 문서의 사실에 묶어 두었고, 프롬프트는 말투를 만들었습니다. LLM의 행동을 조정하는 법을 배운 초기 경험이었고, 모든 규칙은 관찰한 실패에서 나왔습니다.'),
        gh=('04_Deep_Daiv/Project/NLP', ('Write-up and prompt log on GitHub', 'GitHub에서 정리 글과 프롬프트 기록 보기')),
        links=[
            ('code', 'https://github.com/heoneyzi/prompted_celebrity', ('Team code', '팀 코드')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- Taste Trip
    dict(
        slug='taste-trip', dom='ai', icon='pin', short='Taste Trip',
        kicker=('Recommender systems · Data · 2024', '추천 시스템 · 데이터 · 2024'),
        title=('A restaurant → café route recommender', '맛집에서 카페까지, 동선 추천'),
        lede=('deep daiv. recommender-systems team project, built from crawled Naver Place reviews.',
              '네이버 플레이스 리뷰를 직접 수집해 만든 deep daiv. 추천 시스템 팀 프로젝트입니다.'),
        card_q=('Recommend a meal, then a café nearby — from a few ratings and 51,705 reviewers’ histories.',
                '평점 몇 개와 리뷰어 51,705명의 이력으로, 식당과 근처 카페를 이어서 추천합니다.'),
        card_v='51,705 × 337', card_l=('reviewers × venues in the score matrix', '리뷰어 × 장소 점수 행렬'),
        outcome=('Streamlit prototype', 'Streamlit 프로토타입'), status='done',
        role=('Team Lead', '팀장'),
        period=('Summer 2024', '2024 여름'),
        team=('deep daiv. recommender-systems team — <b>Jiheon Kang (Team Lead)</b>', 'deep daiv. 추천 시스템 팀 — <b>강지헌(팀장)</b>'),
        glance=dict(
            topic=('Map apps rank places one at a time, but a day out is usually a pair: a meal, then a café nearby.',
                   '지도 앱은 장소를 하나씩 추천하지만, 실제 나들이는 보통 “식사 후 근처 카페”처럼 짝으로 움직입니다.'),
            did=('Led the team and built the three-stage Naver Place crawler (venues → reviews → reviewer histories), cutting a test run from 9 min 20 s to about 4 min 20 s.',
                 '팀을 이끌며 네이버 플레이스 3단계 크롤러(장소 → 리뷰 → 리뷰어 이력)를 만들었고, 시험 실행 시간을 9분 20초에서 약 4분 20초로 줄였습니다.'),
            result=('A 51,705-user × 337-venue matrix, four recommenders (popularity, content-based, matrix factorisation, hybrid) and a demo that walks a user from a restaurant to a café.',
                    '사용자 51,705명 × 장소 337곳 행렬, 추천 모델 4종(인기도, 콘텐츠 기반, 행렬 분해, 하이브리드), 그리고 식당에서 카페로 이어 주는 데모를 만들었습니다.'),
        ),
        question=[
            ('Collaborative filtering learns from other people (“users who liked what you liked also went to…”); content-based filtering compares the places themselves, using review keywords and categories, so it works even for a brand-new user. With only 1.6 % of the matrix filled, sparsity was the central problem.',
             '협업 필터링은 다른 사람들로부터 배우고(“당신과 취향이 비슷한 사람은 여기도 갔어요”), 콘텐츠 기반 필터링은 리뷰 키워드와 업종으로 장소 자체를 비교해 처음 온 사용자에게도 추천할 수 있습니다. 행렬의 1.6%만 채워져 있어 희소성이 가장 큰 문제였습니다.'),
        ],
        steps=[
            (('Collect', '수집'), ('Crawl 337 venues (204 restaurants, 133 cafés) and their reviewers’ histories.', '장소 337곳(식당 204곳, 카페 133곳)과 리뷰어 이력을 수집했습니다.')),
            (('Fill the gaps', '빈칸 채우기'), ('Impute sparse users from similar users before training.', '학습 전에 비슷한 사용자로 희소한 사용자의 빈칸을 채웠습니다.')),
            (('Recommend', '추천'), ('Compare popularity, content-based, matrix-factorisation and hybrid models.', '인기도, 콘텐츠 기반, 행렬 분해, 하이브리드 모델을 비교했습니다.')),
            (('Walk the route', '동선 연결'), ('Six quick ratings, then a restaurant and a café in the same area.', '평점 6개만 입력하면 같은 지역의 식당과 카페를 차례로 추천합니다.')),
        ],
        kpis=[
            ('337', ('venues crawled', '수집한 장소'), ('204 restaurants · 133 cafés', '식당 204곳 · 카페 133곳')),
            ('51,705', ('reviewers in the matrix', '행렬에 담긴 리뷰어'), ('1.6 % of cells filled', '칸의 1.6%만 채워짐')),
            ('≈ 2×', ('faster crawler test run', '빨라진 크롤러 시험 실행'), ('9 min 20 s → about 4 min 20 s', '9분 20초 → 약 4분 20초')),
        ],
        scope=('The historical accuracy scores were not archived, so no recommendation accuracy is claimed.',
               '당시 정확도 점수는 보관되지 않아 추천 정확도는 주장하지 않습니다.'),
        vision=('Most of the work was data — collecting it, cleaning it, filling its gaps. That respect for the data pipeline carried straight into my biological projects.',
                '작업의 대부분은 데이터였습니다. 모으고, 다듬고, 빈칸을 채우는 일이었죠. 데이터 파이프라인을 꼼꼼히 다루는 습관은 그대로 생물학 프로젝트로 이어졌습니다.'),
        gh=('04_Deep_Daiv/Project/R.S', ('Crawler notes and code on GitHub', 'GitHub에서 크롤러 노트와 코드 보기')),
        links=[
            ('code', 'https://github.com/heoneyzi/Taste_Trip_Recommender-System', ('Original code', '원본 코드')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- Genomics study
    dict(
        slug='genomics-study', dom='dna', icon='book', short='Genomics study',
        kicker=('Study · YAI Functional Genomics · 2026', '공부 · YAI Functional Genomics · 2026'),
        title=('Learning biology as an engineer', '공학도의 생물학 공부'),
        lede=('Two seasons of Functional Genomics study at Yonsei AI (YAI) — the notebook where GDTR and our VCC entry began.',
              'Yonsei AI(YAI) Functional Genomics 팀의 두 시즌 공부 기록 — GDTR과 VCC 참가가 시작된 노트입니다.'),
        card_q=('From the central dogma to genome language models and single-cell Perturbation — where GDTR and VCC began.',
                '센트럴 도그마에서 유전체 언어모델과 단일세포 Perturbation까지 — GDTR과 VCC가 시작된 곳.'),
        card_v='69', card_l=('curated notes, every author credited', '작성자를 모두 밝혀 정리한 노트'),
        outcome=('Season 2 Team Lead', '시즌 2 팀장'), status='live',
        role=('Member (season 1) · Team Lead (season 2)', '시즌 1 팀원 · 시즌 2 팀장'),
        period=('Jan 2026 – ongoing', '2026.01 – 진행 중'),
        team=('Season 1: 조윤진, 구민선, 박수빈, 정유민, <b>강지헌</b> · Season 2: <b>강지헌 (lead)</b>, 정유민, 김민석, 김서진, 김서연, 이동현',
              '시즌 1: 조윤진, 구민선, 박수빈, 정유민, <b>강지헌</b> · 시즌 2: <b>강지헌(팀장)</b>, 정유민, 김민석, 김서진, 김서연, 이동현'),
        glance=dict(
            topic=('I came to biology from electrical engineering. The fastest way I know to learn a field is to read, write it up, argue about it in a team — then test the open questions.',
                   '저는 전기전자공학에서 생물학으로 왔습니다. 제가 아는 가장 빠른 방법은 읽고, 정리하고, 팀에서 토론한 뒤, 남은 질문을 직접 시험하는 것입니다.'),
            did=('Season 1 (Jan–Apr 2026): CAFA 6, then a journal club on genome language models where I presented whether their embeddings beat simple baselines. Season 2 (Jul 2026–): I lead the team through Perturbation biology into the Virtual Cell Challenge.',
                 '시즌 1(2026.1–4): CAFA 6 이후 유전체 언어모델 저널클럽에서 “임베딩이 단순한 기준보다 나은가”를 발표했습니다. 시즌 2(2026.7–): 팀장으로서 Perturbation 생물학을 공부하고 Virtual Cell Challenge에 도전하고 있습니다.'),
            result=('The journal club’s last meeting proposed the layer-by-layer Evo 2 analysis that became GDTR; season 2 became our VCC 2026 entry.',
                    '저널클럽 마지막 모임에서 나온 “Evo 2 층별 분석” 제안이 GDTR이 되었고, 시즌 2는 VCC 2026 참가로 이어졌습니다.'),
        ),
        question=[
            ('How does a DNA sequence turn into what a cell does — and how much of that path can today’s models follow? The notes stay in their original Korean, with every teammate credited by name and a guide that suggests a reading order.',
             'DNA 서열은 어떻게 세포의 행동이 될까요? 그리고 지금의 모델은 그 길을 얼마나 따라갈 수 있을까요? 노트는 한국어 원문 그대로 두고, 팀원 모두의 이름을 밝혔으며, 읽는 순서를 안내하는 가이드를 붙였습니다.'),
        ],
        steps=[
            (('Primer', '기초'), ('Biology for ML people: DNA, RNA, proteins, splicing and mutations.', 'ML 전공자를 위한 생물학: DNA, RNA, 단백질, 스플라이싱, 변이.')),
            (('Season 1 · proteins & genome LMs', '시즌 1 · 단백질과 유전체 LM'), ('CAFA 6, then five journal-club weeks on genome language models.', 'CAFA 6, 이어서 유전체 언어모델 저널클럽 5주.')),
            (('Season 2 · cells', '시즌 2 · 세포'), ('Foundation-model limits, drug-response models and VCC 2025 lessons.', '파운데이션 모델의 한계, 약물 반응 모델, VCC 2025의 교훈.')),
            (('Into experiments', '실험으로'), ('Open questions became GDTR and our VCC 2026 pipeline.', '남은 질문이 GDTR과 VCC 2026 파이프라인이 되었습니다.')),
        ],
        kpis=[
            ('69', ('curated notes', '정리한 노트'), ('from 107 Notion pages', 'Notion 107페이지에서')),
            ('2', ('seasons of team study', '팀 공부 시즌'), ('Jan 2026 – ongoing', '2026.01 – 진행 중')),
            ('GDTR · VCC', ('research that started here', '여기서 시작된 연구'), ('paper + ongoing challenge', '논문 + 진행 중인 챌린지')),
        ],
        scope=None,
        vision=('Coming from engineering, I learn biology by building on it. Every note is a rule of nature I wanted to understand — and several of those questions became my research.',
                '공학에서 온 저는 생물학을 직접 다뤄 보며 배웁니다. 노트 하나하나는 이해하고 싶었던 자연의 규칙이었고, 그중 몇 개의 질문은 제 연구가 되었습니다.'),
        gh=('03_Study/Genomics', ('All 69 notes on GitHub', 'GitHub에서 노트 69편 보기')),
        cta=('All 69 notes, with a reading order and a timeline, are in the Study repository on GitHub.', '노트 69편 전체와 읽는 순서, 타임라인은 GitHub의 Study 저장소에 있습니다.'),
        links=[],
    ),
    # ------------------------------------------------------------------------------------------- Hallucination
    dict(
        slug='hallucination', dom='ai', icon='eye', short='Hallucination study',
        kicker=('Study · Multimodal LLMs · 2025–26', '공부 · 멀티모달 LLM · 2025–26'),
        title=('Why multimodal AI sees things that aren’t there', '멀티모달 AI는 왜 없는 것을 봤다고 할까'),
        lede=('A year of study on hallucination in vision and audio-visual language models, with two small pilot experiments.',
              '비전·오디오-비디오 언어모델의 환각을 1년간 공부하고, 작은 파일럿 실험 두 개를 진행했습니다.'),
        card_q=('Why do vision and audio-visual LLMs describe objects and sounds that aren’t there?',
                '비전·오디오-비디오 LLM은 왜 없는 물체와 소리를 말할까?'),
        card_v='4 / 6', card_l=('mismatched audio–video pairs called “matching”', '“일치”라고 답한 불일치 오디오-비디오 쌍'),
        outcome=('26 notes · 2 pilots', '노트 26편 · 파일럿 2개'), status='done',
        role=('All notes and experiments', '노트와 실험 전체 작성'),
        period=('May 2025 – May 2026', '2025.05 – 2026.05'),
        team=('<b>Jiheon Kang</b>; phase 1 with teammate Heejae Yang', '<b>강지헌</b> · 1단계는 Heejae Yang과 함께'),
        glance=dict(
            topic=('Multimodal models mention objects that aren’t in the picture or sounds that were never played — often because the language side answers from habit instead of evidence.',
                   '멀티모달 모델은 사진에 없는 물체나 들리지 않은 소리를 말하곤 합니다. 언어 쪽이 근거 대신 습관으로 답하기 때문인 경우가 많습니다.'),
            did=('Studied attention-based fixes for image–text models, proposed a “look like a human” segment-guided attention idea, then set up an audio-visual LLM (video-SALMONN 2+) and ran two pilot tests.',
                 '이미지-텍스트 모델의 어텐션 기반 완화 기법을 공부하고, “사람처럼 보기”라는 세그먼트 기반 어텐션 아이디어를 제안했습니다. 이어서 오디오-비디오 LLM(video-SALMONN 2+)을 세팅해 파일럿 실험 두 개를 했습니다.'),
            result=('The model called <b>4 of 6</b> mismatched audio–video pairs “matching”, and on questions whose answer was “none of the above” it never chose that option (0 of 9).',
                    '모델은 불일치한 오디오-비디오 6쌍 중 <b>4쌍</b>을 “일치”라고 답했고, 정답이 “해당 없음”인 9문항에서는 그 보기를 한 번도 고르지 않았습니다.'),
        ),
        question=[
            ('Attention — how much each generated word looks back at image, audio or text — is a cheap, training-free lens on hallucination, and most fixes I studied work by reshaping it at inference time. So it is the natural first thing to measure on a new model.',
             '어텐션(생성되는 단어가 이미지·오디오·텍스트를 얼마나 참고하는지)은 환각을 들여다보는 값싸고 학습이 필요 없는 창입니다. 제가 공부한 완화 기법 대부분도 추론 시점에 어텐션을 다시 조정합니다. 그래서 새 모델에서 가장 먼저 재 볼 대상입니다.'),
        ],
        steps=[
            (('Survey the causes', '원인 정리'), ('Data, model, training and inference — and the families of inference-time fixes.', '데이터, 모델, 학습, 추론 단계별 원인과 추론 시점 완화 기법의 갈래를 정리했습니다.')),
            (('Propose an idea', '아이디어 제안'), ('“Look like a human”: let each generated word choose which segmented object to attend to.', '“사람처럼 보기”: 생성되는 단어마다 어떤 객체 영역을 볼지 고르게 합니다.')),
            (('Move to audio + video', '오디오·비디오로 확장'), ('Set up video-SALMONN 2+ and log where its attention goes.', 'video-SALMONN 2+를 세팅하고 어텐션이 어디로 가는지 기록했습니다.')),
            (('Run two pilots', '파일럿 2개'), ('AVHBench (12 videos) and DAVE (50 samples).', 'AVHBench(영상 12개)와 DAVE(샘플 50개).')),
        ],
        kpis=[
            ('4 / 6', ('mismatched pairs judged “matching”', '“일치”로 판단한 불일치 쌍'), ('AVHBench, 12 videos', 'AVHBench 영상 12개')),
            ('46%', ('audio–visual alignment accuracy', '오디오-비주얼 정렬 정확도'), ('DAVE, 50 samples · chance 20 %', 'DAVE 50개 · 무작위 20%')),
            ('0 / 9', ('“none of the above” chosen when correct', '정답이 “해당 없음”일 때 고른 횟수'), ('the model never abstained', '모델은 한 번도 기권하지 않음')),
        ],
        scope=('Small pilot experiments from an individual study, not a paper.', '개인 공부의 작은 파일럿 실험이며 논문이 아닙니다.'),
        vision=('Asking where a model looks when it invents something is an interpretability question — the same lens I now use on DNA models.',
                '모델이 없는 것을 지어낼 때 어디를 보고 있는지 묻는 것은 결국 해석의 문제입니다. 지금 DNA 모델에 쓰는 것과 같은 시선입니다.'),
        gh=('03_Study/Hallucination', ('Notes and pilot experiments on GitHub', 'GitHub에서 노트와 파일럿 실험 보기')),
        cta=('The 26 study notes and both pilot experiments are in the Study repository on GitHub.', '공부 노트 26편과 파일럿 실험 두 개는 GitHub의 Study 저장소에 있습니다.'),
        links=[
            ('read', 'https://stib.ee/lq1I', ('Newsletter #95', '뉴스레터 #95')),
            ('read', 'https://stib.ee/eXmJ', ('Newsletter #114', '뉴스레터 #114')),
            ('read', 'https://stib.ee/7npK', ('Newsletter #125', '뉴스레터 #125')),
        ],
    ),
    # ------------------------------------------------------------------------------------------- Writing
    dict(
        slug='writing', dom='write', icon='pen', short='Newsletter & Magazine',
        kicker=('Writing · deep daiv. Contents Team · 2024–26', '글쓰기 · deep daiv. 콘텐츠팀 · 2024–26'),
        title=('Explaining AI to everyone', '모두를 위한 AI 글쓰기'),
        lede=('Nine issues of the weekly newsletter 위클리 딥 다이브 and three pieces for magazine vol.0, under the pen name 에디터 져니 (“Editor Journey”).',
              '주간 뉴스레터 “위클리 딥 다이브” 9편과 매거진 vol.0의 글 3편을 필명 “에디터 져니”로 썼습니다.'),
        card_q=('Nine newsletter issues and three magazine pieces as 에디터 져니, turning papers into everyday analogies.',
                '“에디터 져니”로 쓴 뉴스레터 9편과 매거진 글 3편. 논문을 일상의 비유로 풀었습니다.'),
        card_v='9 + 3', card_l=('newsletter issues + magazine pieces', '뉴스레터 + 매거진 글'),
        outcome=('Newsletter Writer · Magazine Editor', '뉴스레터 필진 · 매거진 에디터'), status='done',
        role=('Weekly AI Newsletter Writer · AI Magazine Editor', '주간 AI 뉴스레터 필진 · AI 매거진 에디터'),
        period=('Aug 2024 – Jan 2026', '2024.08 – 2026.01'),
        team=('deep daiv. Contents Team', 'deep daiv. 콘텐츠팀'),
        glance=dict(
            topic=('Research only matters if people can follow it. The deep daiv. Contents Team publishes a weekly AI newsletter and a printed magazine for newcomers.',
                   '연구는 사람들이 따라올 수 있어야 의미가 있습니다. deep daiv. 콘텐츠팀은 주간 AI 뉴스레터와 입문자를 위한 인쇄 매거진을 만듭니다.'),
            did=('Wrote nine newsletter issues on multimodal AI (Mar 2025 – Jan 2026) and, as a magazine editor, three pieces for vol.0 (Aug – Dec 2024).',
                 '멀티모달 AI를 다룬 뉴스레터 9편(2025.3 – 2026.1)을 썼고, 매거진 에디터로서 vol.0에 글 3편(2024.8 – 12)을 실었습니다.'),
            result=('Several issues grew out of — or into — my own research: hallucination (#95, #114, #125) and video grounding (#109).',
                    '몇몇 호는 제 연구에서 나왔거나 연구로 이어졌습니다. 환각(#95, #114, #125)과 비디오 그라운딩(#109)이 그렇습니다.'),
        ),
        question=[
            ('Each issue takes one or two recent papers — full-duplex speech models, missing modalities, LVLM hallucination, LLaVA, video grounding, watermarking, attention sinks — and explains them with everyday analogies for a general Korean audience.',
             '매 호마다 최신 논문 한두 편(전이중 음성 모델, 모달리티 결손, LVLM 환각, LLaVA, 비디오 그라운딩, 워터마킹, 어텐션 싱크 등)을 골라 일반 독자도 이해할 수 있게 일상의 비유로 풀었습니다.'),
        ],
        steps=[
            (('Pick one idea', '아이디어 하나 고르기'), ('One frontier paper per issue, chosen for why it matters.', '매 호마다 왜 중요한지가 분명한 최신 논문 하나를 고릅니다.')),
            (('Find the analogy', '비유 찾기'), ('Explain it through something everyday — an eyewitness, a smartphone, a highlight reel.', '목격자 진술, 스마트폰, 하이라이트 영상처럼 일상의 무언가로 설명합니다.')),
            (('Edit for newcomers', '입문자를 위한 편집'), ('For the magazine: a concept primer, an interview and a first-coding guide.', '매거진에는 개념 입문, 인터뷰, 첫 코딩 안내를 썼습니다.')),
        ],
        kpis=[
            ('9', ('newsletter issues', '뉴스레터 발행'), ('#84 → #125 · Mar 2025 – Jan 2026', '#84 → #125 · 2025.03 – 2026.01')),
            ('3', ('magazine pieces', '매거진 글'), ('deep daiv. vol.0 · Dec 2024', 'deep daiv. vol.0 · 2024.12')),
            ('4', ('issues tied to my research', '제 연구와 이어진 호'), ('hallucination × 3, video grounding × 1', '환각 3편, 비디오 그라운딩 1편')),
        ],
        scope=None,
        vision=('Explaining an idea in plain words is the best test of whether I understand it. I want my research to be readable by the people it is meant to help.',
                '쉬운 말로 설명할 수 있어야 제가 제대로 이해한 것입니다. 제 연구가 도움을 주려는 사람들도 읽을 수 있기를 바랍니다.'),
        gh=('04_Deep_Daiv/Contents', ('All issues and drafts on GitHub', 'GitHub에서 모든 호와 초안 보기')),
        cta=('Every issue, the archived drafts and the magazine excerpt are collected in the Deep_Daiv repository on GitHub.', '모든 호와 초안, 매거진 발췌본은 GitHub의 Deep_Daiv 저장소에 모아 두었습니다.'),
        links=[],
        issues=[
            ('#84', '2025-03-26', 'AI와 말동무를 맺을 수 있을까', 'Can AI become a conversation partner?', 'https://stib.ee/FtxG'),
            ('#91', '2025-05-14', '잃어버린 정보를 찾아서', 'In search of lost information', 'https://stib.ee/kwXH'),
            ('#95', '2025-06-11', 'AI의 목격자 진술, 과연 믿을 수 있을까', 'Can we trust AI’s eyewitness testimony?', 'https://stib.ee/lq1I'),
            ('#96', '2025-06-18', '스마트폰은 당신보다 당신을 더 잘 알고 있다', 'Your smartphone knows you better than you do', 'https://stib.ee/ny5I'),
            ('#105', '2025-08-20', 'LLaVA는 어떻게 멀티모달의 기준이 되었는가?', 'How did LLaVA become the multimodal baseline?', 'https://stib.ee/uIvI'),
            ('#109', '2025-09-17', 'AI는 어떻게 동영상 하이라이트를 만들까?', 'How does AI make video highlights?', 'https://stib.ee/PbLJ'),
            ('#114', '2025-10-22', 'LVLM의 환각은 어떻게 측정할까?', 'How do we measure LVLM hallucination?', 'https://stib.ee/eXmJ'),
            ('#121', '2025-12-10', 'AI가 만든 가짜들의 홍수에서 살아남는 법', 'Surviving the flood of AI-made fakes', 'https://stib.ee/ZJTK'),
            ('#125', '2026-01-07', 'Attention Mechanism의 함정', 'The trap in the attention mechanism', 'https://stib.ee/7npK'),
        ],
    ),
]

BY_SLUG = {p['slug']: p for p in PROJECTS}
FEATURED = ['gdtr', 'vcc2026', 'cafa6', 'phenofocus', 'ftf-vtg', 'bi-cot']
MORE = ['geoflowagent', 'bu-net', 'persona-chatbot', 'taste-trip']
STUDY = ['genomics-study', 'hallucination', 'writing']
